[metadata]
name = facebench
version = 0.1.0
author = CHOP
author_email =
description = A modular benchmarking library for 3D face reconstruction.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/..
license = ?
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Topic :: Scientific/Engineering :: Artificial Intelligence
    Intended Audience :: Science/Research

[options]
packages = find:
python_requires = >=3.8
include_package_data = True
install_requires =
    numpy
    scipy
    tqdm
    cvxpy
    open3d


[options.package_data]
facebench = jason?

[options.entry_points]
console_scripts =
    facebench = facebench.cli:main

[tool:pytest]
testpaths = tests
